apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-go
  name: hello-go
  namespace: default
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: hello-go
  type: ClusterIP