apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-dotnet
  name: hello-dotnet
  namespace: default
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: hello-dotnet
  type: ClusterIP